### PR TITLE
Typewriter

### PR DESCRIPTION
**Pull request by davidfig**
Add a typewriter mode setting to Zen to keep cursor vertically centered on the screen where possible.

### CODE REVIEW

**Comment by rm-code** [comment]
@davidfig 
I just tested it and it works fine :+1: 

Maybe the description in the config should be updated to "Keeps the cursor vertically centered where possible."?

**Comment by davidfig** [comment]
I updated the description as suggested. Thanks for the great work on this plugin!

**Comment by rm-code** [comment]
> Thanks for the great work on this plugin!

Just to clarify - I'm not a dev :smile:

**Comment by davidfig** [comment]
Welp, thanks for taking a look anyway. Is the dev active? I have a few other features that I'd like to add to turn Atom into a better non-code writing experience. I thought this would be a good jumping off place. If not I'll fork and build it out with a different name.

**Comment by rm-code** [comment]
As far as I know @braver is the current maintainer of the Zen Plugin and yes, he is active.

**Comment by davidfig** [comment]
Cool. Thanks!

**Comment by braver** [comment]
Yeah, I'm looking after this one. Super busy week though, will look into this asap!

**Comment by braver** [comment]
Works well enough, but is it as jumpy on your end too? Although I guess if you're writing stuff it's fine...

**Comment by braver** [comment]
One thing before I pull this: it needs to properly disable if I switch it off, without having to toggle Zen mode.

**Pull request merged**
