### PR TITLE
Add option to toggle the gutter when Zen is active

### PR DESCRIPTION
**Pull request by rm-code**
For some reason Zen didn't hide the gutter for me by default. I added an option which allows you to toggle it now.

Best wishes,
Robert

### CODE REVIEW

**Comment by rm-code** [comment]
Pushed a second commit which adds a custom order to the preferences view.

**Comment by rm-code** [comment]
Updated the commits to fix an issue with the zen.less file.

**Comment by braver** [comment]
This conflicts with the state of master now that the other things are pulled in. Could you fix that?

**Comment by rm-code** [comment]
Done!

**Comment by braver** [comment]
Awesome!

**Pull request merged**
