### PR TITLE
Add setting to hide / show the minimap when zen is active

### PR DESCRIPTION
**Pull request by rm-code**
Another small add-on I wrote for myself. Maybe you are interested in merging it into the default plugin.

Best wishes,
Robert

### CODE REVIEW

**Comment by braver** [comment]
Seems to work, except for one thing: The width of each line is shortened by the width of the minimap. This needs to be compensated for.

**Comment by rm-code** [comment]
I noticed that, but that's the default behavior of the minimap plugin I think. It does the same thing outside of zen mode too:
screenshot 2015-05-05 21 47 23
screenshot 2015-05-05 21 47 31

**Comment by braver** [comment]
Yes, that's true, but Zen is supposed to wrap at the width defined for the "preferred line length", at the line-wrap indicator. So, lines become too short with the minimal visible.

**Comment by rm-code** [comment]
I'm not sure if I can fix this on my own, but I'll leave the PR open for now.

**Comment by braver** [comment]
No problem. I noticed a similar problem with the width of the scrollbar, so I need to dig into this myself anyway.

**Comment by braver** [comment]
I know it's been a while, but dealing with the width not exactly matching the line wrap settings is just beyond me. I found no easy, reliable way to check for the scrollbar, also everything changes as soon as go beyond what fits on the screen. So I'm like whatever on accuracy and this feature would be nice so why the heck not. If you can update it so it doesn't conflict I'll happily merge it.

**Comment by rm-code** [comment]
Will do, but I'll wait till you merged #73 so I can also add a menu order for this one.

**Comment by rm-code** [comment]
Fixed the merge conflicts.

**Comment by braver** [comment]
Thanks! :+1:

**Pull request merged**
